version: '3.7'

services:
  django_app:
    build:
      context: ./django_app
    ports:
      - 8002:8000
    volumes: 
      - ./django_app/code:/code
      - ./django_app/data:/data
    command: ["dev.run.sh"]
    depends_on:
      - django_db
    env_file:
      - env_files/dev.env

  django_db:
    image: postgres:14.2-alpine3.15
    env_file:
      - env_files/dev.env
    volumes:
      - django_db_data_dev:/var/lib/postgresql/data

volumes:
  django_db_data_dev:
