version: '3.7'

services:
  djangoapp:
    build:
      context: ./djangoapp
    ports:
      - 8002:8000
    volumes: 
      - ./djangoapp/code:/code
      - ./djangoapp/data:/data
    command: ["dev.run.sh"]
    depends_on:
      - djangodb
    env_file:
      - env_files/django.dev.env

  djangodb:
    image: postgres:14.2-alpine3.15
    env_file:
      - env_files/django.dev.env
    volumes:
      - djangodb_data_dev:/var/lib/postgresql/data

  pi_worker:
    build:
      context: ./pi_worker
    volumes:
      - ./pi_worker/code:/code
      - /sys:/sys
    devices:
      - /dev/gpiomem:/dev/gpiomem
    env_file:
      - env_files/pi.dev.env
    depends_on:
      - djangoapp
      
volumes:
  djangodb_data_dev:
