# Generated by Django 4.0.3 on 2022-03-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_buttonsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('tamper', models.BooleanField()),
                ('tamperCO', models.IntegerField()),
                ('burner', models.BooleanField()),
                ('burnerCO', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
