# Generated by Django 4.0.3 on 2022-03-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sensorstation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorstation',
            name='name',
            field=models.CharField(default='station', max_length=12),
        ),
    ]
