# Generated by Django 4.0.3 on 2022-03-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datapoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='burnerCO',
            new_name='burnerco',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='tamperCO',
            new_name='tamperco',
        ),
    ]
